### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by yarikoptic** [templateflow/python-client#1]
I thought to contribute a bit to datalad related code, but I am scared to break anything so masterfully crafted.  If only there was at least a basic unit test, I could have gained assurance of my competency instead of a later discovery of my arrogance.

**Comment by oesteban** [comment]
On its way...

**Comment by oesteban** [comment]
There is one test now :D

**Comment by yarikoptic** [comment]
Hm, where? Best to close with references to commit hexsha or https://help.github.com/articles/closing-issues-using-keywords/

**Comment by oesteban** [comment]
751950c2df78c5d619712682f428d72eb869611c and 67e72f0c12ede4b4d4d0cbeedb3e4631b07e0c9f
