### ISSUE TITLE
BUG: Updating templateflow does not update the repo

### ISSUE THREAD

**Issue by oesteban** [templateflow/python-client#11]
For S3-backed systems, this requires 1) identifying that this is an update; 2) unzip new files in the skeleton.

For Datalad-backed systems, this requires 1) identifying that this is an update; 2) `datalad update --merge -r`.

**Comment by effigies** [comment]
Yeah, I'm not really sure how things work without datalad. I guess you could include a repo revision hash that also goes into S3, make a best-effort check for the single S3 file and re-download if the hash has changed?
