### ISSUE TITLE
`tpl-onavg` dataset inaccessible via datalad

### ISSUE THREAD

**Issue by prioux** [templateflow/python-client#112]
I can't download `tpl-onavg` at all. I tried with datalad or with direct wget commands, and I've tried finding the files from other sources too and they also have disappeared. Can anyone try this please?

**Comment by effigies** [comment]
This should be resolved. The issue was that there were multiple S3 remotes specified in datalad, so none got autoenabled. Two have been marked dead, so future clones should work as expected.
