### ISSUE TITLE
Suggestion: rename argument resolution to res in api.

### ISSUE THREAD

**Issue by wiheto** [templateflow/python-client#14]
Only a small thing. But all other input arguments seem to follow the BIDS tags structure of the filename except resolution (where intuitively it would be res). Was puzzled for a few minutes why I was getting an empty list returning when trying to specify res='02' before realizing this should be resolution. 

Unless there is some reason why this is written out in full?

**Comment by oesteban** [comment]
@effigies: how shorthand names are dealt in pybids? Is it possible to query for `ses` instead of `session`?

**Comment by effigies** [comment]
I don't think so. We had `alias` at one point that allowed you to use either `acq` or `acquisition`, but I think that's just been removed altogether.

**Comment by oesteban** [comment]
> Unless there is some reason why this is written out in full?

Is there any reason to maintain aliases? Do you think your suggestion would be satisfied with an error message that tries to match entities starting with the alias and asks you whether you meant "resolution" instead of "res" (and so on so forth).

**Comment by oesteban** [comment]
Let's close this for now. It can be a little annoying to some, but it is more maintainable to use pybids without hacks.
