### ISSUE TITLE
Implement a ``get_citation``

### ISSUE THREAD

**Issue by oesteban** [templateflow/python-client#33]
```Python
def get_citation(template, bibtex=False) -> list:
    ...
    return citations
```
The idea is to be able to generate template information in boilerplates automatically.

**Comment by mgxd** [comment]
Looking more into this, there is potential to automate this process. 

Each template contains a `template_description.json` with the necessary information tucked into 2 fields,`HowToAcknowledge` and `ReferencesAndLinks` ([Example 1](https://github.com/templateflow/tpl-MNI152Lin/blob/8068dd61f848941b90e63dc02cd3a13015c4df2c/template_description.json#L5), [Example 2](https://github.com/templateflow/tpl-fsLR/blob/f82f453208008cbaaa4e138b4174c397502ffe2b/template_description.json#L5)). Currently, there is no standard for `HowToAcknowledge`, making it difficult to automatically extract the correct entries in `ReferencesAndLinks`.

By either setting a standard, or adding a new field (`RequiredReferencesIndexes`?) to hold indexes of required references, it should make it much easier to implement the above
