### ISSUE TITLE
Add `update()` call when importing templateflow

### ISSUE THREAD

**Issue by mgxd** [templateflow/python-client#44]
To greatly simplify users updating their templateflow skeletons as templates are added / change.

- stick a call to `templateflow.conf.update()` in `templateflow.__init__.py`
- allow users to *freeze* current skeleton by setting environmental variable, i.e. `TEMPLATEFLOW_AUTOUPDATE=0`
- fail gracefully and inform users when trying and failing to update skeleton

**Comment by oesteban** [comment]
I would add to this:

- remove the post-installation hook

**Comment by oesteban** [comment]
BTW the call should be `templateflow.conf.update(local=True, overwrite=False)`

If a skeleton needs to be upgraded, then that should be done intentionally by the user (or fMRIPrep) with `templateflow.conf.update(local=False, overwrite=False)`

**Comment by mgxd** [comment]
> If a skeleton needs to be upgraded, then that should be done intentionally by the user (or fMRIPrep) with `templateflow.conf.update(local=False, overwrite=False)`

This just bit me in https://github.com/poldracklab/fmriprep-rodents/pull/10/commits/a6bd87fcf1c0aed3bdade807b97def71a597947c. It should be easy for users to ensure they are working with the latest templates, WDYT about adding a flag (maybe `--fetch-latest-templates`) to allow users to run an update with `overwrite=True`?

**Comment by mgxd** [comment]
Ah nevermind, this is #58
