### ISSUE TITLE
Datalad-free fallback

### ISSUE THREAD

**Issue by effigies** [templateflow/python-client#5]
If `datalad.api` cannot be imported, perhaps stubs can be used to simply construct the path and run `os.path.exists()` to check whether the link can be dereferenced.

Related: [neurostars #3619](https://neurostars.org/t/3619), [neurostars #3639](https://neurostars.org/t/3639)

**Comment by yarikoptic** [comment]
or just issue a warning and assume that all data is there?  if it is not there and needed, it would fail anyways

**Comment by effigies** [comment]
But the problem is `templateflow.get` (or whatever) wraps `datalad.get` (or whatever), which is how the path is actually resolved.
