### ISSUE TITLE
TemplateFlow should re-index the BIDS layout after update

### ISSUE THREAD

**Issue by oesteban** [templateflow/python-client#58]
Currently, when `TEMPLATEFLOW_HOME` has been updated in the same python session, the index of the archive remains out-of-date.

**Comment by oesteban** [comment]
I feel we left something untested within #59.

For instance, we are getting this issue now on SDCFlows - https://app.circleci.com/pipelines/github/nipreps/sdcflows/513/workflows/652d10c5-19e7-4715-9b54-c76cc023d964/jobs/1908

**Comment by mgxd** [comment]
is this happening sporadically? I haven't been able to reproduce locally.

**Comment by mgxd** [comment]
can this be closed @oesteban ?
