### ISSUE TITLE
Release 0.7.0 incorrectly posted

### ISSUE THREAD

**Issue by oesteban** [templateflow/python-client#65]
(some stale release seems to have made it to Pypi)

https://app.circleci.com/pipelines/github/templateflow/python-client/715/workflows/c81ec05c-6e9c-485d-bd2a-fa9da0f748e3/jobs/1131

**Comment by mgxd** [comment]
IIRC, the only difference from the release on PyPI and the `0.7.0` tag was the change log. By the time the GH Actions workflow caught it, it already hit the release job on Circle.

**Comment by oesteban** [comment]
I had the impression that the version string was 0.0.0 and then I saw the failed builds and thought there is a problem. It was safer to cut clean.
