### ISSUE TITLE
Feature request: list available files for a template

### ISSUE THREAD

**Issue by sportnoah14** [templateflow/python-client#90]
Hi, I'm just starting out with templateflow and one thing I thought may be nice is to have a function that can list all available files related to that template. For example:

```
from templateflow import api as tflow
tflow.get_files("MNI152NLin6Asym")
```

It would simply list the files available to use associated with this template without first having to download everything. Maybe it can be integrated with `get_metadata()` or `get()`? Hope this is possible.

**Comment by oesteban** [comment]
This is definitely a good idea. I would say the API should be `api.list()` though - would that seem reasonable?

**Comment by sportnoah14** [comment]
@oesteban that sounds great. Do you think the `api.list()` could accept arguments similar as `api.get()` to filter for different datatypes and descriptors such as mask or a T1/T2?

**Comment by oesteban** [comment]
Yes, I think that would be fundamental. And it's not that hard to expose
because get() does need to internally list() with those filters
