### ISSUE TITLE
``BIDSLayout`` is now including dotfolders (i.e., `.git`, `.datalad`, etc.)

### ISSUE THREAD

**Issue by oesteban** [templateflow/python-client#98]
For some reason, it seems they have started to be included. Any ideas @effigies @mgxd ?

**Comment by mgxd** [comment]
Can you share a minimal example? I wasn't able to verify this using the latest pybids

**Comment by mgxd** [comment]
I think that is intended, [based on the docstring](https://github.com/bids-standard/pybids/blob/5ea3103b6dada5d3fd02cdec7d6498817d76f366/bids/layout/index.py#L54-L62). They should probably be converted to regex

**Comment by oesteban** [comment]
Yes, I didn't mean this is a PyBIDS issue
